Allow dynamic default message with variables
am-team/luna_park pull request #95
Opened 2020-12-24 16:42 UTC by CaptainPhilipp

2020-12-25 20:06 UTC, CaptainPhilipp commented on lib/luna_park/errors/adaptive.rb
> +      def default_message
Возможно лучше сделать `#localized_message ` и `#default_message ` приватными

2020-12-31 10:19 UTC, kudrin requested changes

2020-12-31 10:19 UTC, kudrin commented on lib/luna_park/errors/adaptive.rb
> +        def message(txt = nil, i18n_key: nil, &build_message)
Возможно стоит:

```ruby
def message(txt = nil, i18n_key: nil, &message_block)
  @message_block = block_given? ? message_block : ->(_) { txt }
  # ...
end

# И тогда
def message(locale: nil)
  @message || localized_message(locale) || build_message || self.class.default_message
end
      
def build_message
  self.class.message_block&.call(details)
end
```

2020-12-31 10:19 UTC, kudrin commented on lib/luna_park/errors/adaptive.rb
>        #   error = TemperatureError.new 'Please do not use fahrenheits'
Точно надо:
Посмотри документирующие комменты, и надо добавить примеров когда у нас сообщение - это блок.

2020-12-31 10:19 UTC, kudrin commented on lib/luna_park/errors/adaptive.rb
> +      def default_message
Не критично, но я всегда за то, что если можно что-то убрать, то лучше убрать.

2021-01-15 09:38 UTC, kudrin approved these changes

2021-01-15 09:38 UTC, kudrin commented on lib/luna_park/errors/adaptive.rb
> +      # @example message is in internalization config with i18n interpolation
Пример фрагмента yaml файл будет не лишним.

2021-01-15 09:38 UTC, kudrin commented on lib/luna_park/errors/adaptive.rb
>        # @return [String] message text
Changelog + version

2021-01-15 13:22 UTC, merged